repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [ '--maxkb=1024' ]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        exclude: migrations
        args:
          - "--max-line-length=120"
        entry: .venv/bin/flake8
        language: system
        types:
          - python
      - id: black
        name: black
        exclude: migrations
        args: [ --check, --diff ]
        entry: .venv/bin/black
        language: system
        types:
          - python
